### ISSUE TITLE
about experiment detail？

### ISSUE THREAD

**Issue by ScarletBlaze** [Xiefan-Guo/CTSDG#3]
Thank you for your excellent work, I would really like to reproduce your model as a baseline for comparison, at your convenience can you tell us the number of training and fine-tuning iterations for each dataset?Thanks ！

**Comment by xiefan-guo** [comment]
Hi, generally, 350,000+150,000 is ok. You can adjust it appropriately.

**Comment by ScarletBlaze** [comment]
> Hi, generally, 350,000+150,000 is ok. You can adjust it appropriately.

Thanks for your reply, but I guess the number of iterations "350K+150K" is about the number of iterations for the celeba and paris datasets, right? So according to the training time mentioned in the paper, is the places2 dataset "(350K*2.5=)875K+150K"?

**Comment by 01SHENyankun** [comment]
> > 你好，一般35万+15万就可以了。你可以适当调整一下。
> 
> 感谢您的回复，但我猜“350K+150K”的迭代次数大约是 celeba 和 paris 数据集的迭代次数，对吧？那么根据论文中提到的训练时间，places2数据集是“(350K*2.5=)875K+150K”吗？

@ScarletBlaze 不好意思，打扰你了，请问你复现出来了嘛，如果成功了，能不能指导我一下，我将不胜感激！I'm sorry to bother you, but you've reappeared. If you succeed, I'd appreciate it if you could guide me!
qq：2635505974
