### ISSUE TITLE
Quantitative evaluation

### ISSUE THREAD

**Issue by youyeg** [Xiefan-Guo/CTSDG#5]
Hi,
Thank you for your great works. I couldn't find a section for quantitative results. Would you provide me with the pipeline with the quantitative results? And are you using irregular masks for different masks or do you use your own masks?
Are they isolated for testing or they are included in the training time too?

**Comment by xiefan-guo** [comment]
Hi, you can refer to the _Experimental Settings_ of the [paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Guo_Image_Inpainting_via_Conditional_Texture_and_Structure_Dual_Generation_ICCV_2021_paper.pdf). The [Irregular Masks](https://nv-adlr.github.io/publication/partialconv-inpainting) provides training and testing splits.

**Comment by youyeg** [comment]
Hi, thank you for your response. I meant the setting that you used for evaluation. e.g. The code for PSSM, PSNR, and LPIPS evaluations, and seeds that you have used for training and so on. I wanted to reproduce the same results for comparison. In your repository, I can see qualitative test code to reproduce reconstructed images.

**Comment by xiefan-guo** [comment]
Hi, the code  used for evaluation is as follows: 
_PSNR & SSIM_: https://github.com/Vious/LBAM_Pytorch
_LPIPS_: https://github.com/richzhang/PerceptualSimilarity

**Comment by 01SHENyankun** [comment]
> 您好，感谢您的回复。我的意思是您用于评估的设置。例如，PSSM、PSNR 和 LPIPS 评估的代码，以及您用于训练的种子等。我想重现相同的结果进行比较。在您的存储库中，我可以看到用于重现重建图像的定性测试代码。

你好，能不能加个好友指导一下

**Comment by youyeg** [comment]
Hi, and thanks for dropping by. I am not sure what is the meaning of what you wrote.

**Comment by 01SHENyankun** [comment]
> Hi, and thanks for dropping by. I am not sure what is the meaning of what you wrote.

![image](https://user-images.githubusercontent.com/84694608/139404888-b675fd4d-0b52-434f-9870-34c95c84e0e0.png)

**Comment by 01SHENyankun** [comment]
> Hi, and thanks for dropping by. I am not sure what is the meaning of what you wrote.

Sorry, I have a problem. It happened when the program was running. Would you please give me some advice

**Comment by Charlieww** [comment]
> Hi, thank you for your response. I meant the setting that you used for evaluation. e.g. The code for PSSM, PSNR, and LPIPS evaluations, and seeds that you have used for training and so on. I wanted to reproduce the same results for comparison. In your repository, I can see qualitative test code to reproduce reconstructed images.

Hello, have you reproduced the code for SSIM, PSNR, and LPIPS evaluations. I did some tests, but I feel the data is wrong. If you do it, please contact me, thank you.
